name: Build and Push Image

on:
    push:
        branches:
            - main
        paths:
            - "Chat2me/**"
            - Dockerfile

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Configure AWS creds
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ vars.ROLE_ARN }}
                aws-region: ${{ vars.AWS_REGION }}

            - name: Login to ECR
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build Docker Image
              run: |
                docker build -t ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPO_NAME }}:${{ github.sha }} .

            - name: Docker Push Image
              run: |
                docker push ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPO_NAME }}:${{ github.sha }}



