name: Terraform Deploy

on:
  workflow_dispatch:

concurrency:
  group: "terraform-deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        TF_VAR_container_port: ${{ secrets.TF_VAR_CONTAINER_PORT }}
        TF_VAR_domain_name: ${{ secrets.TF_VAR_DOMAIN_NAME }}
        TF_VAR_subdomain: ${{ secrets.TF_VAR_SUBDOMAIN }}
        TF_VAR_project_name: ${{ secrets.TF_VAR_PROJECT_NAME }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -var="image_tag=${{ github.sha }}"

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve -var="image_tag=${{ github.sha }}"

      - name: Wait for ECS service to stabilize
        run: sleep 60

      - name: Health Check
        run: |
          curl -f https://${{ vars.APP_DOMAIN }}/health