name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
        TF_VAR_container_port: ${{ secrets.TF_VAR_CONTAINER_PORT }}
        TF_VAR_domain_name: ${{ secrets.TF_VAR_DOMAIN_NAME }}
        TF_VAR_subdomain: ${{ secrets.TF_VAR_SUBDOMAIN }}
        TF_VAR_project_name: ${{ secrets.TF_VAR_PROJECT_NAME }}

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Destroy
        working-directory: infra
        run: terraform destroy -auto-approve